# Generated by Django 5.2.6 on 2025-09-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('t-shirt', 'T-shirt'), ('jacket', 'Jacket'), ('shoes', 'Shoes'), ('socks', 'Socks'), ('ball', 'Ball')], default='jersey', max_length=20),
        ),
    ]
