# Generated by Django 5.2.6 on 2025-10-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_store_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('tshirt', 'T-Shirt'), ('jacket', 'Jacket'), ('shoes', 'Shoes'), ('socks', 'Socks'), ('ball', 'Ball')], default='jersey', max_length=20),
        ),
    ]
